<template>
  <section class="hn-reports">
    <!-- Page header -->
    <div class="dash-top">
      <div class="dash-title">
        <h1>Reports</h1>
        <p class="subtle">
          Reports Overview <span class="sep">›</span> Analyze and generate detailed reports.
        </p>
      </div>
    </div>

    <!-- KPI row -->
    <div class="kpi-row">
      <div class="kpi kpi-blue">
        <div class="kpi-left">
          <div class="kpi-label">Occupancy Rate</div>
          <div class="kpi-ico"><font-awesome-icon icon="chart-line" /></div>
        </div>
        <div class="kpi-value">84%</div>
      </div>

      <div class="kpi kpi-teal">
        <div class="kpi-left">
          <div class="kpi-label">Avg. Length of Stay</div>
          <div class="kpi-ico"><font-awesome-icon icon="clock" /></div>
        </div>
        <div class="kpi-value">4.2</div>
      </div>

      <div class="kpi kpi-orange">
        <div class="kpi-left">
          <div class="kpi-label">Incident Reports</div>
          <div class="kpi-ico"><font-awesome-icon icon="file-lines" /></div>
        </div>
        <div class="kpi-value">4</div>
      </div>

      <div class="kpi kpi-red">
        <div class="kpi-left">
          <div class="kpi-label">Med Errors</div>
          <div class="kpi-ico"><font-awesome-icon icon="triangle-exclamation" /></div>
        </div>
        <div class="kpi-value">2</div>
      </div>
    </div>

    <!-- Recent Reports panel -->
    <section class="panel glass">
      <div class="panel-top">
        <div class="filters">
          <div class="search-row">
            <font-awesome-icon class="search-ico" icon="magnifying-glass" />
            <input v-model="q" class="search" placeholder="Search..." type="text" />
          </div>

          <button class="dd" type="button">
            <span>All Types</span>
            <font-awesome-icon icon="chevron-down" />
          </button>

          <button class="dd" type="button">
            <span>All Units</span>
            <font-awesome-icon icon="chevron-down" />
          </button>

          <button class="dd" type="button">
            <span>From</span>
            <font-awesome-icon icon="chevron-down" />
          </button>

          <button class="dd" type="button">
            <span>To</span>
            <font-awesome-icon icon="chevron-down" />
          </button>
        </div>

        <button class="gen-btn" type="button">
          Generate Report <font-awesome-icon icon="chevron-down" />
        </button>
      </div>

      <div class="panel-title">
        <span class="title-ico"><font-awesome-icon icon="file-lines" /></span>
        Recent Reports
      </div>

      <div class="table-wrap">
        <table class="rep-table">
          <colgroup>
            <col class="c-check" />
            <col class="c-name" />
            <col class="c-type" />
            <col class="c-date" />
            <col class="c-by" />
            <col class="c-actions" />
          </colgroup>

          <thead>
            <tr>
              <th><input class="chk" type="checkbox" v-model="allSelected" @change="toggleAll" /></th>
              <th>Report Name <font-awesome-icon class="sort-ico" icon="chevron-down" /></th>
              <th>Type <font-awesome-icon class="sort-ico" icon="chevron-down" /></th>
              <th>Date <font-awesome-icon class="sort-ico" icon="chevron-down" /></th>
              <th>Generated By <font-awesome-icon class="sort-ico" icon="chevron-down" /></th>
              <th class="th-right">Actions <font-awesome-icon class="sort-ico" icon="chevron-down" /></th>
            </tr>
          </thead>

          <tbody>
            <tr v-for="r in filtered" :key="r.id">
              <td>
                <input class="chk" type="checkbox" v-model="selected" :value="r.id" />
              </td>

              <td>
                <div class="name-cell">
                  <img class="avatar" :src="r.avatar" alt="" />
                  <div class="nm">
                    <div class="nm-top">{{ r.name }}</div>
                    <div class="nm-sub">{{ r.sub }}</div>
                  </div>
                </div>
              </td>

              <td>
                <span class="pill" :class="r.typePill">{{ r.type }}</span>
              </td>

              <td>
                <div class="date-cell">
                  <div class="d1">{{ r.date }}</div>
                  <div class="d2">{{ r.time }}</div>
                </div>
              </td>

              <td class="by-cell">{{ r.by }}</td>

              <td class="actions">
                <button class="act" type="button">View</button>
                <button class="act" type="button">Export</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="table-foot">
        <div class="foot-left">Showing 1 to 5 of 18 reports</div>

        <div class="foot-right">
          <div class="pager">
            <button class="pg" type="button"><font-awesome-icon icon="angle-left" /></button>
            <button class="pg active" type="button">1</button>
            <button class="pg" type="button">2</button>
            <button class="pg" type="button"><font-awesome-icon icon="angle-right" /></button>
          </div>

          <button class="perpage" type="button">
            10 / page <font-awesome-icon icon="chevron-down" />
          </button>
        </div>
      </div>
    </section>

    <!-- Bottom grid -->
    <section class="bottom-grid">
      <!-- Comment panel -->
      <section class="panel glass comment">
        <div class="comment-left">
          <img class="avatar lg" :src="comment.authorAvatar" alt="" />
          <div class="c-body">
            <div class="c-name">{{ comment.author }}</div>
            <div class="c-role">{{ comment.role }}</div>
            <div class="c-msg">{{ comment.text }}</div>
          </div>
        </div>

        <button class="link" type="button">
          View All Reports <font-awesome-icon icon="chevron-right" />
        </button>
      </section>

      <!-- Metrics Summary -->
      <section class="panel glass metrics">
        <div class="panel-title">Metrics. Summary</div>

        <div class="metrics-grid">
          <div class="m-card">
            <div class="m-head">Occupancy Rate</div>
            <div class="line-mock">
              <svg viewBox="0 0 220 70" preserveAspectRatio="none" class="line-svg">
                <path
                  d="M0,44 C20,20 40,55 60,40 C80,25 100,50 120,35 C140,20 160,40 180,18 C200,30 210,24 220,28"
                  fill="none"
                  stroke="rgba(79,119,255,.85)"
                  stroke-width="3"
                />
                <circle cx="180" cy="18" r="4" fill="rgba(79,119,255,.95)" />
              </svg>

              <div class="bubble">
                <div class="b1">84%</div>
                <div class="b2">30%</div>
              </div>

              <div class="days">
                <span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span><span>Mon</span>
              </div>
            </div>
          </div>

          <div class="m-card">
            <div class="m-head">Incidents Types</div>
            <div class="pie-row">
              <div class="legend">
                <div class="leg">
                  <span class="dot blue"></span> Patient Fails, 50%
                </div>
                <div class="leg">
                  <span class="dot pink"></span> Medication Errors, 25%
                </div>
                <div class="leg">
                  <span class="dot orange"></span> Equipment issues, 25%
                </div>
              </div>

              <div class="donut">
                <svg viewBox="0 0 120 120" class="donut-svg">
                  <circle class="trk" cx="60" cy="60" r="42" />
                  <circle class="seg seg1" cx="60" cy="60" r="42" />
                  <circle class="seg seg2" cx="60" cy="60" r="42" />
                  <circle class="seg seg3" cx="60" cy="60" r="42" />
                </svg>
                <div class="donut-center">
                  <div class="check">
                    <font-awesome-icon icon="check" />
                  </div>
                </div>
              </div>
            </div>

            <button class="link" type="button">
              View All Reports <font-awesome-icon icon="chevron-right" />
            </button>
          </div>
        </div>
      </section>

      <!-- Task Completion -->
      <section class="panel glass taskcomp">
        <div class="panel-title">Task Completion</div>

        <div class="bars">
          <div class="bar-row">
            <div class="bar-label"><span class="dot green"></span> Completed</div>
            <div class="bar-track">
              <div class="bar-fill" style="width:69%"></div>
            </div>
            <div class="bar-val">69%</div>
          </div>

          <div class="bar-row">
            <div class="bar-label"><span class="dot orange"></span> In Progress</div>
            <div class="bar-track">
              <div class="bar-fill orange" style="width:25%"></div>
            </div>
            <div class="bar-val">25%</div>
          </div>

          <div class="bar-row">
            <div class="bar-label"><span class="dot pink"></span> Pending</div>
            <div class="bar-track">
              <div class="bar-fill pink" style="width:25%"></div>
            </div>
            <div class="bar-val">25%</div>
          </div>
        </div>
      </section>
    </section>
  </section>
</template>

<script setup>
import { computed, ref } from "vue";

/* search */
const q = ref("");

/* selection */
const selected = ref([]);
const allSelected = ref(false);

function toggleAll() {
  if (allSelected.value) {
    selected.value = filtered.value.map((x) => x.id);
  } else {
    selected.value = [];
  }
}

/* data */
const reports = ref([
  {
    id: 1,
    name: "Patient Roster Report",
    sub: "Patient Care",
    type: "Patient Care",
    typePill: "p-blue",
    date: "Apr 23, 2024",
    time: "10:15 AM",
    by: "Sarah Thompson, RN",
    avatar: "https://i.pravatar.cc/64?img=12",
  },
  {
    id: 2,
    name: "Task Completion Report",
    sub: "Tasks & Productivity",
    type: "Tasks & Productivity",
    typePill: "p-green",
    date: "Apr 22, 2024",
    time: "6:45 PM",
    by: "Sarah Thompson, RN",
    avatar: "https://i.pravatar.cc/64?img=12",
  },
  {
    id: 3,
    name: "Staff Scheduling Report",
    sub: "Staffing",
    type: "Staffing",
    typePill: "p-orange",
    date: "Apr 21, 2024",
    time: "8:00 PM",
    by: "Sarah Thompson, RN",
    avatar: "https://i.pravatar.cc/64?img=12",
  },
  {
    id: 4,
    name: "Medication Administration Report",
    sub: "Medication Related",
    type: "Medication Related",
    typePill: "p-purple",
    date: "Apr 20, 2024",
    time: "3:30 PM",
    by: "Sarah Thompson, RN",
    avatar: "https://i.pravatar.cc/64?img=12",
  },
  {
    id: 5,
    name: "Incident & Safety Report",
    sub: "Incidents",
    type: "Incidents",
    typePill: "p-orange2",
    date: "Apr 20, 2024",
    time: "11:00 AM",
    by: "Sarah Thompson, RN",
    avatar: "https://i.pravatar.cc/64?img=12",
  },
]);

const filtered = computed(() => {
  const s = q.value.trim().toLowerCase();
  if (!s) return reports.value;
  return reports.value.filter((r) => r.name.toLowerCase().includes(s));
});

const comment = ref({
  author: "Sarah Thompson - RN",
  role: "Head Nurse / Nurse Unit Manager",
  text:
    "The Task Completion Report has been updated, staff productivity has improved to 67% this week. Let's keep up the great work!",
  authorAvatar: "https://i.pravatar.cc/64?img=12",
});
</script>

<style scoped>
.hn-reports{ padding: 18px 18px 24px; }
.sep{ margin: 0 6px; opacity: .55; }
.dash-title h1{ margin:0; font-size: 30px; font-weight: 900; letter-spacing:-0.02em; }
.dash-title p{ margin: 6px 0 0; font-size: 14px; }

/* KPI row */
.kpi-row{
  display:grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
  margin: 12px 0 14px;
}
.kpi{
  border-radius: 14px;
  padding: 14px 16px;
  color: #fff;
  display:flex;
  align-items:center;
  justify-content:space-between;
  box-shadow: 0 10px 24px rgba(0,0,0,0.10);
  min-height: 70px;
}
.kpi-left{ display:flex; flex-direction:column; gap: 8px; }
.kpi-label{ font-weight: 800; font-size: 14px; opacity: 0.96; }
.kpi-ico{ opacity: .85; font-size: 14px; }
.kpi-value{ font-weight: 900; font-size: 34px; line-height: 1; letter-spacing: -0.03em; }

.kpi-blue{ background: linear-gradient(135deg, #4f77ff, #2f56ff); }
.kpi-teal{ background: linear-gradient(135deg, #4cc3b8, #23b5a8); }
.kpi-red{ background: linear-gradient(135deg, #ff6c6c, #ff4a4a); }
.kpi-orange{ background: linear-gradient(135deg, #ffb35a, #ff8c3a); }

/* Panel (matches your base.css panel look) */
.panel{
  border: 1px solid var(--line);
  border-radius: 14px;
  background: linear-gradient(180deg, rgba(255,255,255,0.92), rgba(255,255,255,0.78));
  box-shadow: var(--panel-glow), var(--panel-shadow);
  overflow: hidden;
}
.glass{ backdrop-filter: blur(10px); }

/* Filters row */
.panel-top{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap: 12px;
  padding: 12px 14px;
  border-bottom: 1px solid rgba(226,232,244,0.85);
  background: linear-gradient(180deg, rgba(248,251,255,0.95), rgba(245,249,255,0.75));
}
.filters{
  display:flex;
  align-items:center;
  gap: 10px;
  flex-wrap: wrap;
  min-width: 0;
}
.search-row{ position: relative; width: 320px; max-width: 54vw; }
.search{
  width:100%;
  border: 1px solid rgba(0,0,0,0.10);
  background: rgba(255,255,255,0.55);
  border-radius: 12px;
  padding: 10px 12px 10px 38px;
  outline: none;
}
.search-ico{ position:absolute; left: 12px; top: 11px; opacity: .65; }

.dd{
  height: 40px;
  min-width: 140px;
  padding: 0 14px;
  border-radius: 12px;
  border: 1px solid rgba(0,0,0,0.12);
  background: rgba(255,255,255,0.60);
  font-size: 14px;
  font-weight: 900;
  color: rgba(30,40,70,0.95);
  display: inline-flex;
  align-items:center;
  justify-content:space-between;
  gap: 10px;
  cursor: pointer;
}

.gen-btn{
  height: 40px;
  padding: 0 14px;
  border-radius: 12px;
  border: 1px solid rgba(0,0,0,0.12);
  background: rgba(255,255,255,0.60);
  font-weight: 900;
  cursor:pointer;
  display:flex;
  align-items:center;
  gap: 10px;
}

/* title */
.panel-title{
  padding: 12px 14px;
  font-weight: 900;
  border-bottom: 1px solid rgba(226,232,244,0.85);
  background: linear-gradient(180deg, rgba(248,251,255,0.95), rgba(245,249,255,0.75));
  display:flex;
  align-items:center;
  gap: 10px;
}
.title-ico{
  width: 28px; height: 28px;
  border-radius: 10px;
  background: rgba(79,119,255,0.14);
  display:grid;
  place-items:center;
  color: #2f56ff;
}

/* Table */
.table-wrap{ padding: 0 12px; overflow:auto; }
.rep-table{
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
  min-width: 980px;
}
.c-check{ width: 44px; }
.c-name{ width: 360px; }
.c-type{ width: 220px; }
.c-date{ width: 170px; }
.c-by{ width: 220px; }
.c-actions{ width: 160px; }

.rep-table th, .rep-table td{
  padding: 12px 10px;
  border-bottom: 1px solid rgba(226,232,244,0.9);
  font-size: 13px;
  color: rgba(30,40,70,0.92);
}
.rep-table thead th{
  font-weight: 900;
  color: rgba(80,90,120,0.75);
  background: rgba(255,255,255,0.28);
}
.th-right{ text-align:right; }
.sort-ico{ margin-left: 6px; opacity: .55; font-size: 11px; }

.chk{
  width: 16px; height: 16px;
  accent-color: #2f56ff;
}

.name-cell{ display:flex; align-items:center; gap: 10px; min-width: 0; }
.avatar{ width: 30px; height: 30px; border-radius: 999px; object-fit: cover; }
.avatar.lg{ width: 44px; height: 44px; }
.nm{ min-width:0; }
.nm-top{
  font-weight: 900;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.nm-sub{
  margin-top: 2px;
  font-size: 11px;
  color: rgba(90,105,130,0.72);
  font-weight: 800;
}
.date-cell .d1{ font-weight: 900; }
.date-cell .d2{ margin-top: 2px; font-size: 11px; color: rgba(90,105,130,0.72); font-weight: 800; }

.by-cell{ white-space: nowrap; overflow:hidden; text-overflow: ellipsis; }

.pill{
  display:inline-flex;
  align-items:center;
  padding: 6px 10px;
  border-radius: 10px;
  font-size: 12px;
  font-weight: 900;
  border: 1px solid rgba(0,0,0,0.06);
}
.p-blue{ background: rgba(79,119,255,0.16); color:#2f56ff; }
.p-green{ background: rgba(67,200,159,0.18); color:#1a8e84; }
.p-orange{ background: rgba(255,179,90,0.18); color:#ff8c3a; }
.p-orange2{ background: rgba(255,179,90,0.18); color:#ff8c3a; }
.p-purple{ background: rgba(155,123,255,0.16); color:#7a5cff; }

.actions{
  display:flex;
  justify-content:flex-end;
  gap: 8px;
}
.act{
  height: 30px;
  padding: 0 12px;
  border-radius: 8px;
  border: 1px solid rgba(47,86,255,0.25);
  background: rgba(47,86,255,0.12);
  color: #2f56ff;
  font-weight: 900;
  cursor:pointer;
}

.table-foot{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap: 12px;
  padding: 10px 14px 12px;
  color: rgba(90,105,130,0.85);
  font-weight: 800;
}
.foot-right{ display:flex; align-items:center; gap: 10px; }
.pager{ display:flex; gap: 6px; }
.pg{
  width: 34px; height: 30px;
  border-radius: 8px;
  border: 1px solid rgba(226,232,244,0.95);
  background: rgba(255,255,255,0.65);
  font-weight: 900;
  cursor:pointer;
}
.pg.active{ background: rgba(47,86,255,0.14); border-color: rgba(47,86,255,0.22); color:#2f56ff; }
.perpage{
  height: 30px;
  padding: 0 10px;
  border-radius: 10px;
  border: 1px solid rgba(226,232,244,0.95);
  background: rgba(255,255,255,0.65);
  font-weight: 900;
  cursor:pointer;
}

/* Bottom grid */
.bottom-grid{
  margin-top: 14px;
  display:grid;
  grid-template-columns: 1.4fr 1fr 0.9fr;
  gap: 14px;
  align-items: start;
}

.comment{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap: 12px;
  padding: 14px;
}
.comment-left{ display:flex; gap: 12px; align-items:flex-start; min-width: 0; }
.c-body{ min-width: 0; }
.c-name{ font-weight: 900; }
.c-role{ margin-top: 2px; font-size: 12px; color: rgba(90,105,130,0.75); font-weight: 800; }
.c-msg{ margin-top: 10px; color: rgba(30,40,70,0.88); font-weight: 700; line-height: 1.35; }

.link{
  border: none;
  background: transparent;
  color: #2f56ff;
  font-weight: 900;
  cursor:pointer;
  display:flex;
  align-items:center;
  gap: 10px;
  white-space: nowrap;
}

.metrics .metrics-grid{
  padding: 12px 14px 14px;
  display:grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}
.metrics{ overflow: visible; }
.metrics-grid {
  overflow: visible;
}
.m-card{
  border: 1px solid rgba(226,232,244,0.95);
  background: rgba(255,255,255,0.55);
  border-radius: 14px;
  padding: 12px;
  overflow: visible;
}
.m-head{ font-weight: 900; margin-bottom: 10px; color: rgba(30,40,70,0.88); }

.line-mock{ position: relative; }
.line-svg{ width: 100%; height: 72px; display:block; }
.bubble{
  position:absolute;
  right: 6px; top: 8px;
  width: 54px; height: 54px;
  border-radius: 999px;
  background: rgba(79,119,255,0.86);
  color: #fff;
  display:grid;
  place-items:center;
  text-align:center;
  box-shadow: 0 10px 18px rgba(0,0,0,0.12);
}
.b1{ font-weight: 900; line-height: 1; }
.b2{ font-size: 11px; font-weight: 900; opacity: .9; margin-top: 2px; }

.days{
  display:flex;
  justify-content: space-between;
  font-size: 11px;
  font-weight: 900;
  color: rgba(90,105,130,0.72);
  margin-top: 6px;
}

.pie-row{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap: 14px;
}
.legend{ min-width: 0; flex: 1 1 auto; display:grid; gap: 8px; font-weight: 800; color: rgba(60,70,95,0.8); font-size: 12px; }
.leg{ display:flex; align-items:center; gap: 8px; white-space: nowrap; }
.dot{
  width: 8px; height: 8px; border-radius: 999px;
  display:inline-block;
}
.dot.blue{ background: rgba(79,119,255,0.95); }
.dot.pink{ background: rgba(255,106,156,0.92); }
.dot.orange{ background: rgba(255,154,61,0.92); }
.dot.green{ background: rgba(67,200,159,0.92); }

.donut{
  position: relative;
  width: 132px; height: 132px;
  flex: 0 0 132px;
  margin-right: 6px;  
}
.donut-svg{ width:132px; height:132px; display: block; transform: rotate(-90deg); }
.trk{
  fill: none;
  stroke: rgba(226,232,244,0.9);
  stroke-width: 14;
}
.seg{
  fill: none;
  stroke-width: 14;
  stroke-linecap: butt;
  stroke-dasharray: 0 999;
  transform-origin: 60px 60px;
}
.seg1{ stroke: rgba(79,119,255,0.95); stroke-dasharray: 132 999; }
.seg2{ stroke: rgba(255,106,156,0.92); stroke-dasharray: 66 999; transform: rotate(158deg); }
.seg3{ stroke: rgba(255,154,61,0.92); stroke-dasharray: 66 999; transform: rotate(237deg); }

.donut-center{
  position:absolute; inset:0;
  display:grid;
  place-items:center;
  pointer-events:none;
}
.check{
  width: 44px; height: 44px;
  border-radius: 999px;
  background: rgba(255,255,255,0.85);
  display:grid;
  place-items:center;
  border: 1px solid rgba(226,232,244,0.9);
  box-shadow: 0 10px 18px rgba(0,0,0,0.10);
  color: rgba(79,119,255,0.95);
}

.taskcomp .bars{ padding: 12px 14px 14px; display:grid; gap: 12px; }
.bar-row{
  display:grid;
  grid-template-columns: 130px 1fr 44px;
  gap: 10px;
  align-items:center;
}
.bar-label{ display:flex; align-items:center; gap: 8px; font-weight: 900; color: rgba(60,70,95,0.85); }
.bar-track{
  height: 10px;
  border-radius: 999px;
  background: rgba(226,232,244,0.9);
  overflow:hidden;
}
.bar-fill{
  height: 100%;
  border-radius: 999px;
  background: rgba(67,200,159,0.9);
}
.bar-fill.orange{ background: rgba(255,154,61,0.92); }
.bar-fill.pink{ background: rgba(255,106,156,0.92); }
.bar-val{ text-align:right; font-weight: 900; color: rgba(60,70,95,0.78); }

/* responsive */
@media (max-width: 1100px){
  .kpi-row{ grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .bottom-grid{ grid-template-columns: 1fr; }
  .search-row{ width: 100%; max-width: unset; }
}
@media (max-width: 640px){
  .kpi-row{ grid-template-columns: 1fr; }
  .panel-top{ flex-direction: column; align-items: stretch; }
  .gen-btn{ width: 100%; justify-content: space-between; }
}
@media (max-width: 520px){
  .pie-row{
    flex-direction: column;
    align-items: flex-start;
  }
  .donut{
    margin-right: 0;
    align-self: center;
  }
}
</style>
